### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedEventArgs
  id: WorkflowApplicationAbortedEventArgs
  children:
  - System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  langs:
  - csharp
  name: WorkflowApplicationAbortedEventArgs
  nameWithType: WorkflowApplicationAbortedEventArgs
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs
  type: Class
  summary: "提供有關已中止的工作流程執行個體資料。"
  remarks: "當工作流程由<xref:System.Activities.WorkflowApplication>已中止時，<xref:System.Activities.WorkflowApplication.Aborted%2A>在叫用處理常式和<xref:System.Activities.WorkflowApplication.Completed%2A>不叫用處理常式。</xref:System.Activities.WorkflowApplication.Completed%2A> </xref:System.Activities.WorkflowApplication.Aborted%2A> </xref:System.Activities.WorkflowApplication>"
  example:
  - "The following code example inspects the WorkflowApplicationAbortedEventArgs passed into the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about why workflow was aborted.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#5](~/add/codesnippet/csharp/t-system.activities.work_4_1.cs)]"
  syntax:
    content: 'public class WorkflowApplicationAbortedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  id: Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  langs:
  - csharp
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "取得所提供的工作流程執行個體中止原因的相關資訊的例外狀況"
  remarks: "當工作流程由<xref:System.Activities.WorkflowApplication>已中止時，<xref:System.Activities.WorkflowApplication.Aborted%2A>在叫用處理常式和<xref:System.Activities.WorkflowApplication.Completed%2A>不叫用處理常式。</xref:System.Activities.WorkflowApplication.Completed%2A> </xref:System.Activities.WorkflowApplication.Aborted%2A> </xref:System.Activities.WorkflowApplication>"
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationAbortedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about why workflow was aborted.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#5](~/add/codesnippet/csharp/p-system.activities.work_6_1.cs)]"
  syntax:
    content: public Exception Reason { get; }
    return:
      type: System.Exception
      description: "所提供的工作流程執行個體中止原因的相關資訊的例外狀況。"
  overload: System.Activities.WorkflowApplicationAbortedEventArgs.Reason*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason*
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
